name: build-test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
     

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: npm run format-check
      - run: npm test
